/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class ChiTietSanPham_GUI extends javax.swing.JFrame {

    /**
     * Creates new form ThemSanPham_GUI
     */
    public ChiTietSanPham_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_north = new javax.swing.JPanel();
        jLabel_chuDe = new javax.swing.JLabel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanel_left = new javax.swing.JPanel();
        jPanel_anh = new javax.swing.JPanel();
        jLabel_anh = new javax.swing.JLabel();
        jPanel_right = new javax.swing.JPanel();
        jLabel_maSanPham = new javax.swing.JLabel();
        jLabel_tenSanPham = new javax.swing.JLabel();
        jLabel_thanhPhan = new javax.swing.JLabel();
        jLabel_xuatXu = new javax.swing.JLabel();
        jLabel_ngaySanXuat = new javax.swing.JLabel();
        jLabel_ngayHetHan = new javax.swing.JLabel();
        jLabel_loSanXuat = new javax.swing.JLabel();
        jLabel_donGia = new javax.swing.JLabel();
        jLabel_loai = new javax.swing.JLabel();
        jLabel_soLuongTon = new javax.swing.JLabel();
        jLabel_tinhTrang = new javax.swing.JLabel();
        jLabelText_maSanPham = new javax.swing.JLabel();
        jLabelText_tenSanPham = new javax.swing.JLabel();
        jLabelText_thanhPhan = new javax.swing.JLabel();
        jLabelText_xuatXu = new javax.swing.JLabel();
        jLabelText_ngaySanXuat = new javax.swing.JLabel();
        jLabelText_ngayHetHan = new javax.swing.JLabel();
        jLabelText_loSanXuat = new javax.swing.JLabel();
        jLabelText_donGia = new javax.swing.JLabel();
        jLabelText_loai = new javax.swing.JLabel();
        jLabelText_soLuongTon = new javax.swing.JLabel();
        jLabelText_tinhTrang = new javax.swing.JLabel();
        jPanel_south = new javax.swing.JPanel();
        jButton_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_chuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_chuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_chuDe.setText("THÔNG TIN SẢN PHẨM");

        javax.swing.GroupLayout jPanel_northLayout = new javax.swing.GroupLayout(jPanel_north);
        jPanel_north.setLayout(jPanel_northLayout);
        jPanel_northLayout.setHorizontalGroup(
            jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_northLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_chuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel_northLayout.setVerticalGroup(
            jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_northLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_chuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane.setDividerLocation(300);
        jSplitPane.setDividerSize(10);

        jPanel_anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_anh.setPreferredSize(new java.awt.Dimension(215, 200));

        javax.swing.GroupLayout jPanel_anhLayout = new javax.swing.GroupLayout(jPanel_anh);
        jPanel_anh.setLayout(jPanel_anhLayout);
        jPanel_anhLayout.setHorizontalGroup(
            jPanel_anhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        jPanel_anhLayout.setVerticalGroup(
            jPanel_anhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jLabel_anh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_anh.setText("Ảnh");

        javax.swing.GroupLayout jPanel_leftLayout = new javax.swing.GroupLayout(jPanel_left);
        jPanel_left.setLayout(jPanel_leftLayout);
        jPanel_leftLayout.setHorizontalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel_anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel_leftLayout.setVerticalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_leftLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel_anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel_left);

        jLabel_maSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_maSanPham.setText("Mã sản phẩm");

        jLabel_tenSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_tenSanPham.setText("Tên sản phẩm");

        jLabel_thanhPhan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_thanhPhan.setText("Thành phần");

        jLabel_xuatXu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_xuatXu.setText("Xuất xứ");

        jLabel_ngaySanXuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_ngaySanXuat.setText("Ngày sản xuất");

        jLabel_ngayHetHan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_ngayHetHan.setText("Ngày hết hạn");

        jLabel_loSanXuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_loSanXuat.setText("Lô sản xuất");

        jLabel_donGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_donGia.setText("Đơn giá");

        jLabel_loai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_loai.setText("Loại");

        jLabel_soLuongTon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_soLuongTon.setText("Số lượng tồn");

        jLabel_tinhTrang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_tinhTrang.setText("Tình trạng");

        jLabelText_maSanPham.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabelText_maSanPham.setText("SP001");

        jLabelText_tenSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_tenSanPham.setText("Thuốc Ho");

        jLabelText_thanhPhan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_thanhPhan.setText("thành phần");

        jLabelText_xuatXu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_xuatXu.setText("xuất xứ");

        jLabelText_ngaySanXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_ngaySanXuat.setText("ngày sản xuất");

        jLabelText_ngayHetHan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_ngayHetHan.setText("ngày hết hạn");

        jLabelText_loSanXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_loSanXuat.setText("lô sản xuất");

        jLabelText_donGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_donGia.setText("giá");

        jLabelText_loai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_loai.setText("loại");

        jLabelText_soLuongTon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_soLuongTon.setText("số lượng tồn");

        jLabelText_tinhTrang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelText_tinhTrang.setText("tình trạng");

        javax.swing.GroupLayout jPanel_rightLayout = new javax.swing.GroupLayout(jPanel_right);
        jPanel_right.setLayout(jPanel_rightLayout);
        jPanel_rightLayout.setHorizontalGroup(
            jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rightLayout.createSequentialGroup()
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_tinhTrang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_soLuongTon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_loai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_donGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_loSanXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ngayHetHan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ngaySanXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_thanhPhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_tenSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_maSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel_xuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelText_maSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_tenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_thanhPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_xuatXu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_ngaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jLabelText_ngayHetHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_loSanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_donGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_loai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_soLuongTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelText_tinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel_rightLayout.setVerticalGroup(
            jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_maSanPham)
                    .addComponent(jLabelText_maSanPham))
                .addGap(16, 16, 16)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelText_tenSanPham))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_thanhPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelText_thanhPhan))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_xuatXu)
                    .addComponent(jLabelText_xuatXu))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ngaySanXuat)
                    .addComponent(jLabelText_ngaySanXuat))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ngayHetHan)
                    .addComponent(jLabelText_ngayHetHan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_loSanXuat)
                    .addComponent(jLabelText_loSanXuat))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_donGia)
                    .addComponent(jLabelText_donGia))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_loai)
                    .addComponent(jLabelText_loai))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_soLuongTon)
                    .addComponent(jLabelText_soLuongTon))
                .addGap(18, 18, 18)
                .addGroup(jPanel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tinhTrang)
                    .addComponent(jLabelText_tinhTrang))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel_right);

        jButton_thoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_thoat.setText("Thoát");

        javax.swing.GroupLayout jPanel_southLayout = new javax.swing.GroupLayout(jPanel_south);
        jPanel_south.setLayout(jPanel_southLayout);
        jPanel_southLayout.setHorizontalGroup(
            jPanel_southLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_southLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jButton_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_southLayout.setVerticalGroup(
            jPanel_southLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_southLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton_thoat)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_north, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_south, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_north, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_south, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietSanPham_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JLabel jLabelText_donGia;
    private javax.swing.JLabel jLabelText_loSanXuat;
    private javax.swing.JLabel jLabelText_loai;
    private javax.swing.JLabel jLabelText_maSanPham;
    private javax.swing.JLabel jLabelText_ngayHetHan;
    private javax.swing.JLabel jLabelText_ngaySanXuat;
    private javax.swing.JLabel jLabelText_soLuongTon;
    private javax.swing.JLabel jLabelText_tenSanPham;
    private javax.swing.JLabel jLabelText_thanhPhan;
    private javax.swing.JLabel jLabelText_tinhTrang;
    private javax.swing.JLabel jLabelText_xuatXu;
    private javax.swing.JLabel jLabel_anh;
    private javax.swing.JLabel jLabel_chuDe;
    private javax.swing.JLabel jLabel_donGia;
    private javax.swing.JLabel jLabel_loSanXuat;
    private javax.swing.JLabel jLabel_loai;
    private javax.swing.JLabel jLabel_maSanPham;
    private javax.swing.JLabel jLabel_ngayHetHan;
    private javax.swing.JLabel jLabel_ngaySanXuat;
    private javax.swing.JLabel jLabel_soLuongTon;
    private javax.swing.JLabel jLabel_tenSanPham;
    private javax.swing.JLabel jLabel_thanhPhan;
    private javax.swing.JLabel jLabel_tinhTrang;
    private javax.swing.JLabel jLabel_xuatXu;
    private javax.swing.JPanel jPanel_anh;
    private javax.swing.JPanel jPanel_left;
    private javax.swing.JPanel jPanel_north;
    private javax.swing.JPanel jPanel_right;
    private javax.swing.JPanel jPanel_south;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
